name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome # Spécifie l'utilisation de Chrome
          headless: true  # Exécute Chrome en mode headless
          record: false  

       
